#!/usr/bin/env sh

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# yabai -m config mouse_follows_focus          on
# yabai -m config focus_follows_mouse          autoraise
# new window spawns to the right if vertical split, or bottom if horizontal split
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_shadow                float
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config window_border                on
yabai -m config window_border_width          6
yabai -m config active_window_border_color   0xff8CABC8
yabai -m config normal_window_border_color   0xff434c5e
yabai -m config insert_feedback_color        0xffd75f5f
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
# set modifier key to command
yabai -m config mouse_modifier               cmd
# modifier key + mouse 1: rearrange windows
yabai -m config mouse_action1                move
# modifier key + mouse 2: resize windows
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  36
yabai -m config bottom_padding               12
yabai -m config left_padding                 12
yabai -m config right_padding                12
yabai -m config window_gap                   12

# space labels
yabai -m space 1 --label one
yabai -m space 2 --label two
yabai -m space 3 --label three
yabai -m space 4 --label four
yabai -m space 5 --label five
yabai -m space 6 --label six
yabai -m space 7 --label seven
yabai -m space 8 --label eight
yabai -m space 9 --label nine
yabai -m space 10 --label ten

# tell yabai which apps to ignore
yabai -m rule --add app="^System Preferences$" sticky=on layer=above manage=off
yabai -m rule --add app="^System Information$" sticky=on layer=above manage=off
yabai -m rule --add app="^Alfred Preferences$" sticky=on layer=above manage=off

yabai -m signal --add event=window_destroyed action="bash /Users/sate/Documents/development/shell/window-focus-on-destroy.sh"

# S K E T C H Y B A R  E V E N T S
# yabai -m signal --add event=window_focused action="sketchybar -m trigger window_focus &> /dev/null"
# yabai -m signal --add event=window_title_changed action="sketchybar -m trigger title_change &> /dev/null"

echo "yabai configuration loaded"

