#!/usr/bin/env sh

spacebar -m config position             top
spacebar -m config height               23
spacebar -m config title                on
spacebar -m config spaces               on
spacebar -m config clock                on
spacebar -m config power                on
spacebar -m config padding_left         20
spacebar -m config padding_right        20
spacebar -m config spacing_left         20
spacebar -m config spacing_right        25
spacebar -m config text_font            "Menlo:bold:12.0"
spacebar -m config icon_font            "Font Awesome 5 Free:Solid:12.0"
spacebar -m config background_color     0xff424C5D
spacebar -m config foreground_color     0xffD8DEE9
spacebar -m config space_icon_color     0xff8CABC8
spacebar -m config power_icon_color     0xff8CABC8
spacebar -m config battery_icon_color   0xff8CABC8
spacebar -m config dnd_icon_color       0xff8CABC8
spacebar -m config clock_icon_color		0xff8CABC8
spacebar -m config right_shell_icon_color     0xff8CABC8
spacebar -m config power_icon_strip      
spacebar -m config space_icon_strip          
spacebar -m config space_icon           
spacebar -m config clock_icon           
spacebar -m config dnd_icon             
spacebar -m config clock_format         "%d/%m/%y %R"
spacebar -m config right_shell          on
spacebar -m config right_shell_icon     
spacebar -m config right_shell_command  "whoami"

echo "spacebar configuration loaded.."

